# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{metadata_cleaner}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavlo Galeta", "Igor Galeta"]
  s.date = %q{2010-09-22}
  s.default_executable = %q{metadata_cleaner}
  s.description = %q{Remove all images metadata (profiles) in directory}
  s.email = %q{superp1987@gmail.com}
  s.executables = ["metadata_cleaner"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/metadata_cleaner.rb",
     "lib/metadata_cleaner/cleaner.rb",
     "lib/metadata_cleaner/railtie.rb",
     "lib/metadata_cleaner/version.rb",
     "lib/tasks/metadata_cleaner.rake"
  ]
  s.homepage = %q{http://github.com/Brainberry/metadata_cleaner}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{metadata_cleaner}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Clear metadata (profiles) from images}
  s.test_files = [
    "test/metadata_cleaner_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

